export const ADD_TEST_RESULTS = "ADD_TEST_RESULTS"
export const ADD_FINAL_RESULT_CALLBACK = "ADD_FINAL_RESULT_CALLBACK"
export const CLEAR_FINAL_RESULT = "CLEAR_FINAL_RESULT"
export const SET_DEPLOYED_RESULT = "SET_DEPLOYED_RESULT"
export const CLEAR_DEPLOYED_RESULT = "CLEAR_DEPLOYED_RESULT"

